`include "urnaeletronica.v"

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module TP_UrnaEletronica(

	//////////// LED //////////
	LEDG,
	LEDR,

	//////////// SW //////////
	SW,

	//////////// SEG7 //////////
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	HEX6,
	HEX7 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// LED //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// SW //////////
input 		    [17:0]		SW;

//////////// SEG7 //////////
output		     [6:0]		HEX0;
output		     [6:0]		HEX1;
output		     [6:0]		HEX2;
output		     [6:0]		HEX3;
output		     [6:0]		HEX4;
output		     [6:0]		HEX5;
output		     [6:0]		HEX6;
output		     [6:0]		HEX7;


//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================


urnaeletronica instancial(.votestatus(LEDG[0]), .control(SW[17:15]), .clock(SW[14]), .valid(SW[13]), .finish(SW[12]), .digit(SW[3:0]), .tisabella(HEX0[6:0]), .tclaudio(HEX1[6:0]), .tfilipe(HEX2[6:0]), .tguilherme(HEX3[6:0]), .tnulo(HEX4[6:0]));



endmodule
